service: go-sample

provider:
  name: aws
  runtime: go1.x
  memorySize: 128
  region: eu-central-1

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  hello:
    handler: bin/hello
    events:
      - http:
          path: hello
          method: get
